// let's imagine this file is autogenerated from the backend
// ideally, we want to keep these api related types in sync
// with the backend instead of manually writing them out

export type BaseEntity = {
    createdAt: number
    updatedAt: number
}

export type Entity<T> = {
    [K in keyof T]: T[K]
} & BaseEntity

export type User = Entity<{
    userID: string
    gameName: string
    tagLine: string
    rating: string
    seasonPlayCount: string
    totalPlayCount: string
    lastScrapedAt: string
}>

export type AuthUser = Entity<{
    username: string
    gameName: string
    tagLine: string
    role: 'ADMIN' | 'USER'
}>

export type AuthResponse = {
    jwt: string
    user: AuthUser
}

export type Song = Entity<{
    songID: string
    title: string
    artist: string
    genre: string
    bpm: string
    imageUrl: string
    isUtage: boolean
    isAvailable: boolean
    version: string
    releaseDate: string
    deleteDate: string
    beatmaps: Beatmap[]
}>

export type Beatmap = Entity<{
    beatmapID: string
    difficulty:
        | 'basic'
        | 'advanced'
        | 'expert'
        | 'master'
        | 'remaster'
        | 'utage'
    level: string
    internalLevel: number | null
    type: 'std' | 'dx'
    totalNotes: number
    tap: number
    hold: number
    slide: number
    touch: number
    break: number
    noteDesigner: string
    maxDxScore: number
}> &
    Song

export type ScoresResponse = {
    scores: Score[]
    nextOffset: number
    hasMore: boolean
}

export type Score = Entity<{
    scoreID: string
    userID: string
    accuracy: string
    maxCombo: number
    dxScore: number
    tapCritical: number
    tapPerfect: number
    tapGreat: number
    tapGood: number
    tapMiss: number
    holdCritical: number
    holdPerfect: number
    holdGreat: number
    holdGood: number
    holdMiss: number
    slideCritical: number
    slidePerfect: number
    slideGreat: number
    slideGood: number
    slideMiss: number
    touchCritical: number
    touchPerfect: number
    touchGreat: number
    touchGood: number
    touchMiss: number
    breakCritical: number
    breakPerfect: number
    breakGreat: number
    breakGood: number
    breakMiss: number
    fast: number
    late: number
    playedAt: string
}> &
    Beatmap
